/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.*;

public class App {
    public static void main(String[] args) {
        // Full path to your CSV file
        String fileName = "cheese_data.csv";

        List<Cheese> cheeseList = CheeseCSVReader.readCheeseData(fileName);
        CheeseCollection collection = new CheeseCollection(cheeseList);

         // Prints all loaded cheeses for checking data if needed
         // collection.printAllCheeses();

         // Run statistics
        System.out.println("\n=== Cheese Statistics ===");
        CheeseStatistics stats = new CheeseStatistics(collection);
        stats.countByMilkTreatment();
        stats.countOrganicHighMoisture();
        stats.mostCommonMilkType();


    }
}
